from __future__ import annotations

import re

# Keys are lowercase phrases/labels searched in resume text; values are normalized skill names
# (aligned with JobSkill / matching where possible). Multi-word keys use substring match; others
# use token-boundary match so "java" does not match inside "javascript".
SKILL_TAXONOMY: dict[str, str] = {
    # Languages & runtimes
    "python": "python",
    "javascript": "javascript",
    "typescript": "typescript",
    "java": "java",
    "kotlin": "kotlin",
    "scala": "scala",
    "rust": "rust",
    "golang": "golang",
    "go lang": "golang",
    "php": "php",
    "ruby": "ruby",
    "swift": "swift",
    "dart": "dart",
    "perl": "perl",
    "r programming": "r",
    "c++": "c++",
    "c#": "c#",
    ".net": ".net",
    "elixir": "elixir",
    "erlang": "erlang",
    "haskell": "haskell",
    "clojure": "clojure",
    "lua": "lua",
    "matlab": "matlab",
    "solidity": "solidity",
    # Web & UI
    "react": "react",
    "react native": "react native",
    "angular": "angular",
    "vue": "vue",
    "vue.js": "vue",
    "svelte": "svelte",
    "next.js": "nextjs",
    "nuxt": "nuxt",
    "jquery": "jquery",
    "htmx": "htmx",
    "webpack": "webpack",
    "vite": "vite",
    "rollup": "rollup",
    "babel": "babel",
    "tailwind": "tailwind css",
    "bootstrap": "bootstrap",
    "sass": "sass",
    "scss": "scss",
    "less": "less",
    "redux": "redux",
    "mobx": "mobx",
    "zustand": "zustand",
    "d3.js": "d3",
    "three.js": "threejs",
    # Backend & APIs
    "fastapi": "fastapi",
    "django": "django",
    "flask": "flask",
    "spring boot": "spring boot",
    "spring framework": "spring",
    "express": "express",
    "nestjs": "nestjs",
    "nest.js": "nestjs",
    "rails": "rails",
    "ruby on rails": "rails",
    "laravel": "laravel",
    "symfony": "symfony",
    "asp.net": "asp.net",
    "graphql": "graphql",
    "grpc": "grpc",
    "rest api": "rest apis",
    "rest apis": "rest apis",
    "openapi": "openapi",
    "swagger": "swagger",
    "web development": "web development",
    "project management": "project management",
    "data analysis": "data analysis",
    "problem solving": "problem solving",
    # Data & persistence
    "sql": "sql",
    "postgresql": "postgresql",
    "postgres sql": "postgresql",
    "pl-sql/t-sql": "sql",
    "pl/sql": "sql",
    "t-sql": "sql",
    "mysql": "mysql",
    "sql server": "sql server",
    "mariadb": "mariadb",
    "sqlite": "sqlite",
    "sqlalchemy": "sqlalchemy",
    "mongodb": "mongodb",
    "redis": "redis",
    "elasticsearch": "elasticsearch",
    "opensearch": "opensearch",
    "cassandra": "cassandra",
    "dynamodb": "dynamodb",
    "cockroachdb": "cockroachdb",
    "neo4j": "neo4j",
    "influxdb": "influxdb",
    "timescaledb": "timescaledb",
    "snowflake": "snowflake",
    "bigquery": "bigquery",
    "redshift": "redshift",
    "planetscale": "planetscale",
    "supabase": "supabase",
    "cosmos db": "cosmos db",
    "firebase": "firebase",
    "oracle": "oracle",
    # Data engineering & ML
    "pandas": "pandas",
    "numpy": "numpy",
    "scipy": "scipy",
    "pytorch": "pytorch",
    "tensorflow": "tensorflow",
    "keras": "keras",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "xgboost": "xgboost",
    "lightgbm": "lightgbm",
    "spark": "apache spark",
    "pyspark": "pyspark",
    "apache spark": "apache spark",
    "hadoop": "hadoop",
    "hive": "hive",
    "kafka": "kafka",
    "apache kafka": "kafka",
    "airflow": "airflow",
    "apache airflow": "airflow",
    "prefect": "prefect",
    "dagster": "dagster",
    "dbt": "dbt",
    "databricks": "databricks",
    "mlflow": "mlflow",
    "kubeflow": "kubeflow",
    "ray": "ray",
    "hugging face": "huggingface",
    "langchain": "langchain",
    "langgraph": "langgraph",
    "llamaindex": "llamaindex",
    "openai": "openai",
    "anthropic": "anthropic",
    "machine learning": "machine learning",
    "deep learning": "deep learning",
    "nlp": "nlp",
    "computer vision": "computer vision",
    "llm": "llm",
    "generative ai": "generative ai",
    "opencv": "opencv",
    "nltk": "nltk",
    "spacy": "spacy",
    "stanza": "stanza",
    # Cloud & infra
    "aws": "aws",
    "amazon web services": "aws",
    "azure": "azure",
    "microsoft azure": "azure",
    "gcp": "gcp",
    "google cloud": "gcp",
    "kubernetes": "kubernetes",
    "docker": "docker",
    "terraform": "terraform",
    "pulumi": "pulumi",
    "ansible": "ansible",
    "chef": "chef",
    "puppet": "puppet",
    "crossplane": "crossplane",
    "helm": "helm",
    "istio": "istio",
    "linkerd": "linkerd",
    "consul": "consul",
    "vault": "vault",
    "nginx": "nginx",
    "envoy": "envoy",
    "traefik": "traefik",
    "haproxy": "haproxy",
    "serverless": "serverless",
    "lambda": "aws lambda",
    "cloudformation": "cloudformation",
    "cdk": "aws cdk",
    "pulumi aws": "pulumi",
    # CI/CD & VCS
    "git": "git",
    "github": "github",
    "gitlab": "gitlab",
    "bitbucket": "bitbucket",
    "jenkins": "jenkins",
    "circleci": "circleci",
    "travis ci": "travis ci",
    "github actions": "github actions",
    "gitlab ci": "gitlab ci",
    "ci/cd": "ci/cd",
    "argocd": "argocd",
    "argo cd": "argocd",
    "fluxcd": "flux",
    "flux": "flux",
    "tekton": "tekton",
    "spinnaker": "spinnaker",
    "buildkite": "buildkite",
    "teamcity": "teamcity",
    "bamboo": "bamboo",
    # Testing & quality
    "pytest": "pytest",
    "unittest": "unittest",
    "jest": "jest",
    "mocha": "mocha",
    "cypress": "cypress",
    "playwright": "playwright",
    "selenium": "selenium",
    "junit": "junit",
    "rspec": "rspec",
    "xunit": "xunit",
    "nunit": "nunit",
    "testng": "testng",
    "postman": "postman",
    "insomnia": "insomnia",
    "k6": "k6",
    "locust": "locust",
    "gatling": "gatling",
    "sonarqube": "sonarqube",
    "eslint": "eslint",
    "prettier": "prettier",
    "black": "black",
    "ruff": "ruff",
    "mypy": "mypy",
    "pylint": "pylint",
    # Observability
    "prometheus": "prometheus",
    "grafana": "grafana",
    "loki": "loki",
    "tempo": "tempo",
    "jaeger": "jaeger",
    "opentelemetry": "opentelemetry",
    "datadog": "datadog",
    "splunk": "splunk",
    "new relic": "new relic",
    "sentry": "sentry",
    "elastic stack": "elastic stack",
    "kibana": "kibana",
    "logstash": "logstash",
    # Mobile & desktop
    "flutter": "flutter",
    "ionic": "ionic",
    "electron": "electron",
    "qt": "qt",
    "xamarin": "xamarin",
    "jetpack compose": "jetpack compose",
    "swiftui": "swiftui",
    # Messaging & async
    "celery": "celery",
    "rabbitmq": "rabbitmq",
    "activemq": "activemq",
    "sqs": "sqs",
    "sns": "sns",
    "pubsub": "pubsub",
    "nats": "nats",
    "pulsar": "pulsar",
    # OS & misc
    "linux": "linux",
    "ubuntu": "ubuntu",
    "debian": "debian",
    "centos": "centos",
    "red hat": "rhel",
    "rhel": "rhel",
    "windows server": "windows server",
    "powershell": "powershell",
    "bash": "bash",
    "zsh": "zsh",
    "vim": "vim",
    "oauth": "oauth",
    "oauth2": "oauth2",
    "oidc": "oidc",
    "jwt": "jwt",
    "saml": "saml",
    "ldap": "ldap",
    "active directory": "active directory",
    "okta": "okta",
    "auth0": "auth0",
    "keycloak": "keycloak",
    "microservices": "microservices",
    "event-driven": "event driven",
    "websocket": "websocket",
    "webrtc": "webrtc",
}

SKILL_ALIASES: dict[str, str] = {
    # JavaScript ecosystem
    "js": "javascript",
    "node.js": "javascript",
    "nodejs": "javascript",
    "node": "javascript",
    "ts": "typescript",
    "es6": "javascript",
    "ecmascript": "javascript",
    # Python / data science
    "py": "python",
    "tf": "tensorflow",
    "torch": "pytorch",
    "sk-learn": "scikit-learn",
    # JVM / backend
    "jdk": "java",
    "jvm": "java",
    "springboot": "spring boot",
    "kt": "kotlin",
    "rb": "ruby",
    "ror": "rails",
    # Web frameworks
    "nextjs": "nextjs",
    "nuxt.js": "nuxt",
    "vuejs": "vue",
    "reactjs": "react",
    "angularjs": "angular",
    "angular 2": "angular",
    "nest js": "nestjs",
    "express.js": "express",
    "expressjs": "express",
    # Data stores
    "postgres": "postgresql",
    "psql": "postgresql",
    "pg": "postgresql",
    "mongo": "mongodb",
    "mongo db": "mongodb",
    "elastic": "elasticsearch",
    "es7": "elasticsearch",
    "mssql": "sql server",
    "ms sql": "sql server",
    "sql server": "sql server",
    "cosmos db": "cosmos db",
    "cosmosdb": "cosmos db",
    # Cloud
    "amazon aws": "aws",
    "amazon s3": "aws",
    "gce": "gcp",
    "google cloud platform": "gcp",
    "k8s": "kubernetes",
    "kube": "kubernetes",
    "ms azure": "azure",
    "azure devops": "azure",
    # ML
    "ml": "machine learning",
    "dl": "deep learning",
    "cv": "computer vision",
    "gen ai": "generative ai",
    "genai": "generative ai",
    "hf": "huggingface",
    "open ai": "openai",
    # DevOps / CI
    "gh actions": "github actions",
    "gha": "github actions",
    "tfc": "terraform",
    "tfstate": "terraform",
    # Observability
    "otel": "opentelemetry",
    "o11y": "opentelemetry",
    # Misc
    "ci/cd": "ci/cd",
    "cicd": "ci/cd",
    "rest": "rest apis",
    "restful": "rest apis",
    "adaptibility": "adaptability",
    "adaptibility skills": "adaptability",
    "adaptability": "adaptability",
    "graphql apollo": "graphql",
    "apollo": "graphql",
    "tailwindcss": "tailwind css",
    "tailwind css": "tailwind css",
    "tailwind ui": "tailwind css",
    "scss/sass": "sass",
    "golang": "golang",
}


def _skill_mentioned(lowered: str, phrase: str) -> bool:
    """Multi-word / long phrases: substring. Single tokens: avoid matching inside longer words."""
    if " " in phrase or len(phrase) >= 24:
        return phrase in lowered
    return re.search(r"(?<![a-z0-9#.+])" + re.escape(phrase) + r"(?![a-z0-9#.+])", lowered) is not None


def normalize_skill(raw_skill: str) -> str:
    skill = raw_skill.strip().lower()
    if not skill:
        return skill
    return SKILL_ALIASES.get(skill, skill)


def extract_skills_from_text(text: str) -> list[str]:
    lowered = text.lower()
    found: set[str] = set()
    for skill in sorted(SKILL_TAXONOMY.keys(), key=len, reverse=True):
        if _skill_mentioned(lowered, skill):
            found.add(SKILL_TAXONOMY[skill])
    for alias in sorted(SKILL_ALIASES.keys(), key=len, reverse=True):
        if _skill_mentioned(lowered, alias):
            found.add(SKILL_ALIASES[alias])
    return sorted(found)
